"""sync models with db.json

Revision ID: 406e259a8930
Revises: 4db91adcf698
Create Date: 2025-06-30 14:44:22.076672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406e259a8930'
down_revision = '4db91adcf698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
