"""empty message

Revision ID: 573d0ed8a1bb
Revises: 709a74b5f613
Create Date: 2025-06-17 14:51:17.244096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573d0ed8a1bb'
down_revision = '709a74b5f613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('button_text_ru',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('button_text_tk',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('button_text_en',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('content_ru',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('content_tk',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('content_en',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('content_en',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('content_tk',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('content_ru',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('button_text_en',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('button_text_tk',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('button_text_ru',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
