"""Fix terms_accepted type to Boolean

Revision ID: 953275becc34
Revises: 
Create Date: 2025-06-30 17:03:22.069130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953275becc34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_request', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('meeting_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.alter_column('terms_accepted', type_=sa.Boolean())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('meeting_date',
               existing_type=sa.String(length=64),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
