"""add portfolio pdf model

Revision ID: b081202a50af
Revises: 55b5fdc22d8d
Create Date: 2025-06-29 18:19:55.437604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b081202a50af'
down_revision = '55b5fdc22d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_pdf', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('portfolio_pdf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
