"""Remove Work model

Revision ID: b1068b728da7
Revises: d22d1dcb57b1
Create Date: 2025-07-11 12:51:50.341983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1068b728da7'
down_revision = 'd22d1dcb57b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title_ru', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title_en', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description_ru', sa.TEXT(), nullable=True),
    sa.Column('description_en', sa.TEXT(), nullable=True),
    sa.Column('tags_ru', sa.BLOB(), nullable=True),
    sa.Column('tags_en', sa.BLOB(), nullable=True),
    sa.Column('main_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content_ru', sa.TEXT(), nullable=True),
    sa.Column('content_en', sa.TEXT(), nullable=True),
    sa.Column('images', sa.BLOB(), nullable=True),
    sa.Column('button_text_ru', sa.VARCHAR(length=255), nullable=True),
    sa.Column('button_text_en', sa.VARCHAR(length=255), nullable=True),
    sa.Column('button_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bg_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
