"""Добавить additional_images в blog

Revision ID: e58a2f91e346
Revises: 9f352ac44db2
Create Date: 2025-06-14 13:50:09.840478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58a2f91e346'
down_revision = '9f352ac44db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_categories')
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('button_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_images', sa.Text(), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=True)
        batch_op.alter_column('read_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('social_media',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('background_image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('button_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('button_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('button_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('button_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('background_image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('social_media',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('read_time',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('additional_images')

    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.alter_column('button_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.create_table('project_categories',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'category_id')
    )
    # ### end Alembic commands ###
